name: Deploy Docker Image to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: $SSH_HOST
          username: $SSH_USERNAME
          key: $SSH_KEY
          script: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull $DOCKER_USERNAME/$IMAGE_NAME:latest
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -d --name $CONTAINER_NAME -p 3000:3000 $DOCKER_USERNAME/$IMAGE_NAME:latest
